"""
inspector.py — Programmatic Appium Inspector

Replicates what Appium Inspector GUI does manually:
1. Connects to a running Appium session
2. Dumps the UI XML hierarchy (driver.page_source)
3. Parses it with ElementTree
4. Extracts element attributes by text, class, or content-desc
5. Writes results to a locators file
"""
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional
import logging

logger = logging.getLogger(__name__)


@dataclass
class ElementInfo:
    """Typed container for a discovered UI element."""
    resource_id:   str = ""
    text:          str = ""
    class_name:    str = ""
    content_desc:  str = ""
    bounds:        str = ""
    clickable:     bool = False
    enabled:       bool = False

    def is_valid(self) -> bool:
        """A locator is only useful if we have at least one stable identifier."""
        return bool(self.resource_id or self.content_desc)


class AppiumInspector:
    """
    Wraps a live Appium driver to extract element locators programmatically.

    Usage:
        inspector = AppiumInspector(driver)
        login_btn = inspector.find_by_text("Login")
        inspector.write_locators({"LOGIN_BUTTON": login_btn}, output_path)
    """

    def __init__(self, driver) -> None:
        self._driver = driver

    def dump_hierarchy(self) -> ET.Element:
        """
        Fetch current screen's UI XML and parse to an Element tree.
        This is the core call Appium Inspector makes under the hood.
        """
        xml_source: str = self._driver.page_source
        try:
            return ET.fromstring(xml_source)
        except ET.ParseError as exc:
            logger.error("Failed to parse page_source XML: %s", exc)
            raise

    def find_by_text(self, text: str) -> Optional[ElementInfo]:
        """Find first element whose 'text' attribute matches exactly."""
        root = self.dump_hierarchy()
        node = root.find(f'.//*[@text="{text}"]')
        return self._node_to_info(node) if node is not None else None

    def find_by_resource_id(self, resource_id: str) -> Optional[ElementInfo]:
        """Find first element by partial resource-id match."""
        root = self.dump_hierarchy()
        for node in root.iter():
            rid = node.attrib.get("resource-id", "")
            if resource_id in rid:
                return self._node_to_info(node)
        return None

    def find_by_class(self, class_name: str, index: int = 0) -> Optional[ElementInfo]:
        """Find element by Android class name (e.g. android.widget.Button)."""
        root = self.dump_hierarchy()
        matches = [n for n in root.iter() if n.attrib.get("class") == class_name]
        return self._node_to_info(matches[index]) if index < len(matches) else None

    def find_all_buttons(self) -> list[ElementInfo]:
        """Return all Button widgets on screen — useful for full-screen audits."""
        root = self.dump_hierarchy()
        return [
            self._node_to_info(n)
            for n in root.iter()
            if "Button" in n.attrib.get("class", "")
        ]

    @staticmethod
    def _node_to_info(node: ET.Element) -> ElementInfo:
        a = node.attrib
        return ElementInfo(
            resource_id  = a.get("resource-id", ""),
            text         = a.get("text", ""),
            class_name   = a.get("class", ""),
            content_desc = a.get("content-desc", ""),
            bounds       = a.get("bounds", ""),
            clickable    = a.get("clickable", "false") == "true",
            enabled      = a.get("enabled",   "false") == "true",
        )

    @staticmethod
    def write_locators(
        locators: dict[str, Optional["ElementInfo"]],
        output_path: Path,
        build_version: str = "unknown",
    ) -> None:
        """
        Write discovered locators to a Python file.
        This file is committed to source control — it's the audit trail.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now(timezone.utc).isoformat()

        lines = [
            f'# AUTO-GENERATED by AppiumInspector — DO NOT EDIT MANUALLY',
            f'# Timestamp : {timestamp}',
            f'# Build     : {build_version}',
            f'# Re-generate: python setup_lesson.py',
            "",
        ]

        for var_name, info in locators.items():
            if info is None:
                lines.append(f'{var_name}_ID    = None  # NOT FOUND in this build')
                lines.append(f'{var_name}_TEXT  = None')
                lines.append(f'{var_name}_CLASS = None')
            else:
                lines.append(f'{var_name}_ID    = "{info.resource_id}"')
                lines.append(f'{var_name}_TEXT  = "{info.text}"')
                lines.append(f'{var_name}_CLASS = "{info.class_name}"')
            lines.append("")

        output_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info("Locators written to %s", output_path)


# ── Demo/Offline Mode: parse a local XML fixture ──────────────────────────
class OfflineInspector(AppiumInspector):
    """
    Parses a local XML file instead of a live driver.
    Used for CI smoke tests when no emulator is available.
    """

    def __init__(self, xml_path: Path) -> None:
        self._xml_path = xml_path

    def dump_hierarchy(self) -> ET.Element:
        return ET.fromstring(self._xml_path.read_text(encoding="utf-8"))
